from ._loadenv import *

PUSHOVER_ENABLED = os.getenv("PUSHOVER_ENABLED")
PUSHOVER_URL = os.getenv("PUSHOVER_URL")
PUSHOVER_USER = os.getenv("PUSHOVER_USER")
PUSHOVER_TOKEN = os.getenv("PUSHOVER_TOKEN")
